### ISSUE TITLE
Test Poly has incorrect geojson format

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-server#1]
@jasonash The test feature 246 doesn't have the right geojson format for a polygon.

You have:
`"coordinates":[[100,0],[101,0],[101,1],[100,1],[100,0]]}`
But it should be
`"coordinates":[[[100,0],[101,0],[101,1],[100,1],[100,0]]]}`

See http://geojson.org/geojson-spec.html#id4

**Comment by jasonash** [comment]
All GeoJSON formats have been fixed. Please try again.

**Comment by jessica-azgs** [comment]
@jasonash still not exactly right. You now have

`"coordinates":[[[100,0]],[[101,0]],[[101,1]],[[100,1]],[[100,0]]]}`

but, like above, it should be

`"coordinates":[[[100,0],[101,0],[101,1],[100,1],[100,0]]]}`

**Comment by jasonash** [comment]
OK, should be fixed.

**Comment by jessica-azgs** [comment]
Great. All good now.
